ckan/templates/package/snippets/package_form.html
ckan/templates/package/snippets/resource_form.html

Prevents HTML5 client-side validation from interfering with CKAN validation

---

ckan/lib/i18n.py

Added the ability to specify translations for the default language

---

ckan/controllers/user.py
ckan/lib/app_globals.py

Made the user list limit configurable

---

ckan/lib/helpers.py

Conflicts:
ckan/lib/helpers.py

backport: Renamed helper to get_site_protocol_and_host and added docstring

---

ckan/controllers/group.py
ckan/templates/organization/read.html

support multi-select facet for organization search page

---

ckan/controllers/package.py

Fixes #
- [X ] includes user-visible changes

success message for adding a related item

---

ckan/controllers/package.py

Fixes #
- [X ] includes user-visible changes

fix English text for related item

---

ckan/config/environment.py

remove jinja2 BytecodeCache

---

ckan/controllers/package.py

fix edit resource of draft dataset

---

ckan/logic/__init__.py
ckan/plugins/interfaces.py
ckan/plugins/toolkit.py
ckanext/datastore/tests/test_chained_action.py
setup.py

support chained action in plugins

---

ckan/templates/organization/members.html

Fixes #
should not include argument inside the _() function

fix organization members translation

---

ckanext/datastore/logic/action.py
ckanext/datastore/logic/auth.py
ckanext/datastore/plugin.py

update datastore with tiggers

---

ckan/lib/helpers.py

fix get_translated()

---

ckan/lib/helpers.py

fix error in get_translated()

---

ckan/model/activity.py

fix broken activity query

---

ckan/controllers/user.py
ckan/logic/action/update.py
ckan/logic/validators.py
ckan/templates/user/edit_user_form.html
ckan/templates/user/perform_reset.html
ckan/tests/controllers/test_user.py
ckan/tests/logic/action/test_update.py

can not modify existing username

---

ckan/controllers/user.py

Fixes #
User's new password is not set on resetting password

fix user reset password

---

ckan/config/environment.py

re-enable jinja2 bytecode caching

---

ckan/config/environment.py

add missing import jinja2

---

ckan/config/environment.py
test-core.ini

use temp dir for jinja2 cache

---

ckan/controllers/user.py

Fixes #
Remove displaying errors from request parameters

login: removing errors generated by request parameters

---

ckan/lib/helpers.py
ckan/logic/action/create.py
ckan/logic/action/delete.py
ckan/logic/action/update.py
ckan/logic/schema.py
ckan/logic/validators.py
ckan/templates/snippets/activities/changed_resource_view.html
ckan/templates/snippets/activities/deleted_resource_view.html
ckan/templates/snippets/activities/new_resource_view.html
ckan/templates/snippets/activity_stream.html

Fixes #
Include optional id in resource_view_create for persistent resource view id 
- [x ] includes bugfix for possible backport

add new validator for resource view id

---

ckanext/datastore/backend/postgres.py

merge fix: accept argmode to datastore_trigger_create

---

ckan/config/routing.py
ckan/controllers/group.py
ckan/templates/group/members.html
ckan/templates/organization/members.html

Adds CSV download button to organization members template. Adds member dump for sysadmins and org/group admins.

Added `member_dump` action to group and organization controllers.

---

changes/6823.feature
ckan/logic/schema.py
ckan/logic/validators.py

merge(dev): manual-ish merge for license choices validator;
- Partial manual merge of upstream PR for license choice validator.

Add License Choices Validator

---

ckan/views/feed.py

Better Feeds & Translatable Feeds

---

ckan/migration/migrate_package_activity.py

Feat/private activity migration

Migrate Private Activities

---

ckan/migration/migrate_package_activity.py

feat(cli): changed package search to sql select;
- Changed `package_search` loop to simple sql select in migration script.

SQL Select Dataset IDs for Activity Migration

---

changes/6713.bugfix
ckanext/datastore/backend/postgres.py
ckanext/datastore/blueprint.py
ckanext/datastore/tests/test_search.py
ckanext/datastore/writer.py

Stream Datastore Dump in Flask View

---

ckan/templates/package/collaborators/confirm_delete.html
ckan/templates/user/confirm_delete.html
ckan/views/dataset.py
ckan/views/group.py
ckan/views/user.py

fix(views): added missing confirm action pages;
- Added missing confirm user delete.
- Added missing usr deleted flash notice.
- Added missing confirm member delete.
- Added missing collaborator delete.
- Added correct package type redirects for collaborator views.

Added Missing Confirm Action Views

---

ckan/views/group.py
ckan/views/resource.py
ckan/views/user.py

Dupe of https://github.com/ckan/ckan/pull/7996 but just for our 2.9 fork/branch

More Flash Messages

---

ckan/lib/mailer.py
ckan/views/user.py

fix(user): pass reset multiple;
- Fix password reset multiple user accounts.

Fix Password Reset w/ Multiple Accounts

---

ckan/templates/package/snippets/resources_list.html

add block for 'Data and Resources' title

---

ckan/lib/navl/validators.py
ckan/logic/schema.py
ckan/templates/admin/index.html
ckan/tests/controllers/test_user.py
ckan/views/admin.py
ckan/views/user.py

Cherry pick/sysadmin UI

---

ckanext/datatablesview/public/datatablesview.js

fix(js): datatables last view;
- Changed local storage key to suffix with view ID.

Fix Datatables Last View

---

.github/workflows/change_log.yml
changes/172.canada.bugfix
ckan/views/feed.py

fix(views): catch exceptions in feed;
- Catch not auth and not found in custom dataset feed view.

Catch Exceptions in Custom Dataset Feed View

---

changes/173.canada.feature
ckan/views/group.py

feat(views): disable group routes;
- Disable group routes.

Disable Unused Group Routes

---

changes/176.canada.feature
ckan/cli/jobs.py

feat(cli): jobs max time;
- Added option for max worker timeout.

Max Worker Timeout for Jobs Worker CLI
