- ckan/lib/helpers.py
A missing alt text is a WCAG 2.0 failure
> Added the missing alt attribute for the gravatar

- ckan/logic/action/get.py
Fixes #2240
Avert SQL warning on search guaranteed to be empty
> avert sqlalchemy warning on package search if no group names to match

- ckan/lib/helpers.py
- ckan/templates/snippets/language_selector.html
Fixes #
if current url is /en/dataset?q=xxxx, then change to another language will generate bad url.
> fix broken url on language toggle

- ckan/controllers/user.py
Fixes #
Remove flash warning for login and assign to error variable which would be passed to render
> login: remove flash error for invalid login

- ckan/public/base/javascript/view-filters.js
- ckanext/datatablesview/controller.py
A workaround to get the datatables extension split and merge user filters using something other than "|" so it doesn't conflict with the "|" in the filter values of our organization names.
> OPN-1659: datatables view - fix conflict with organization name

- ckanext/datatablesview/templates/datatables/datatables_form.html
- ckanext/datatablesview/templates/datatables/datatables_view.html
Fixes #
Display labels for columns in datatablesview if user sets labels in data dictionary for a resource. Default to `field.id` if no label is set for a field in the data dictionary for the resource.
> display label from data dictionary (when available) for a field in datatablesview

- ckan/lib/cli.py
Fixes #
- Gathers the indexed packages from solr via the `package_search` action, in 100 row intervals.
- Gets all of the package ids from a database query on the `Package` model.
- Checks if an indexed package is NOT in the database package table.
- Clears the orphaned indexed packages. (the `clear` call has debug logging in the method)
> Added `remove-orphans` sub-command to `search-index` cli command.

- ckan/templates/package/read.html
- ckan/templates/package/resources.html
- ckan/templates/package/snippets/resources.html
feat(templates): prevent resource manage in archive view;
- Do not render manage action links while viewing resource archives.
> Resttrict Manage Resource in Archive Viewing

- ckan/lib/helpers.py
- ckan/views/user.py
- ckanext/datapusher/templates-bs2/datapusher/resource_data.html
- ckanext/datapusher/templates/datapusher/resource_data.html
fix(templates): bs alerts, user reset view;
- Fixed output of multiple validation errors for user reset password form.
- Changed `alert-error` to `alert-danger` for wet/bs.
> WET/BS Danger Alerts, and Multiple User Password Reset Validation Messages

- ckan/public/base/javascript/modules/data-viewer.js
- ckan/templates/package/snippets/resource_view.html
feat(modules): adds dynamic source delay to iframes for data viewer;
- Add iFrame source load delay.
@wardi as discussed, the lazy load does not work when the iframe is at top of viewport as the viewport api is available well before the page loads. So I have expanded the CKAN `data-viewer` module to accept a frame source and delay attribute. And then use these to set the iFrame's `src` attribute after that delay.
From testing on a medium sized DataStore resource with a DataTable view, it saved `0.08` to `0.11` seconds of load time. Which is fairly significant. (EDIT: messed up stats because I don't know how to read milliseconds apparently)
> Dynamic Load w/ Delay for Data Viewer Module (Resource Views)

- ckan/cli/jobs.py
- ckan/lib/jobs.py
- ckan/logic/action/get.py
- ckan/logic/schema.py
feat(logic): limit and offset for job list;
- Added params to `job_list` logic action method.
@wardi seems like there is kind of an issue with how to limit/offset the job lists here, because of the case of multiple queue. It is fine for us of course because we only use on Redis queue. But when putting this upstream, I am not sure how to get around that :/
> Job List Limit & Offset

- ckanext/datastore/logic/action.py
fix(logic): ds delete;
- Call `datastore_delete` action via toolkit in `datastore_records_delete`.
Related: https://github.com/ckan/ckanext-dsaudit/pull/2
> Datastore Records Delete Action Fix

- ckanext/datastore/logic/action.py
feat(logic): allow contextual connection;
- Use contextual DB connection in `datastore_run_triggers` to allow temp db tables.
> Use Contextual DB Connection in datastore_run_triggers

- changes/175.canada.changes
- ckanext/datastore/blueprint.py
feat(views): ds dump exclude _id;
- Always exclude the `_id` field from DataStore Dump blueprint.
> Exclude _id from DataStore Dump View

- changes/178.canada.bugfix
- ckan/logic/schema.py
- ckan/templates/user/perform_reset.html
- ckan/views/user.py
Add in a `user_perform_reset_form_schema` schema and use it in the `PerformResetView` class instead of the view class' `_get_form_password` which prevented the framework from doing its normal schema/validation stuff.
> Perform Reset Schema

- changes/180.canada.changes
- ckanext/datastore/writer.py
Fix/ds writer xml element names
- Added regex substitutions for XML element names.
> Datastore Dump XML Element Names

- changes/182.canada.changes
- ckan/lib/authenticator.py
Fixes #
Change the log level in `default_authenticate` from `debug` to `info` for the canada fork only. Related to https://github.com/open-data/ckanext-security/pull/8
> change log level to info in default authenticator

- changes/183.canada.bugfix
- ckanext/datatablesview/blueprint.py
Fixes #
Display accented characters properly in Excel for filtered results downloaded using datatablesview.
> Filtered download bugfix

- changes/181.a.canada.bugfix
- changes/181.b.canada.changes
- changes/181.canada.feature
- changes/183.canada.bugfix
- ckan/lib/helpers.py
- ckan/public/base/javascript/modules/table-toggle-more.js
- ckanext/datastore/backend/postgres.py
- ckanext/datastore/logic/action.py
- ckanext/datastore/logic/schema.py
- ckanext/datatablesview/blueprint.py
> DataStore Foreign Keys

- changes/184.canada.changes
- ckan/templates/macros/form.html
fix(templates): markdown help;
- Update markdown help to our limits of MD.
- Fix translations not working for our setup.
- Translate the actual popup contents.
Dependent: https://github.com/open-data/ckanext-canada/pull/1520
we are no longer allowing headings in our markdown rendering for a11y purposes. So excluding that from the help popup and replacing it with some more useful things. Also removing the "full markdown" doc link as the markdown render does not support a lot of the stuff found in the markdown docs, so better to not send the user there. E.g. they find tables and try to make a markdown table etc., these don't render in CKAN. Just added some more generic things that users can use like numbered lists, formatted links, and block quotes.
> Markdown Help Changes and Translating

- changes/185.canada.feature
- ckan/cli/search_index.py
- ckan/lib/plugins.py
- ckan/lib/search/__init__.py
- ckan/lib/search/jobs.py
- ckan/logic/action/update.py
- ckan/logic/auth/update.py
- ckan/public/base/css/main.css
- ckan/public/base/javascript/modules/progress-bar.js
- ckan/public/base/javascript/webassets.yml
- ckan/templates/admin/base.html
- ckan/templates/admin/search_rebuild.html
- ckan/templates/group/edit_base.html
- ckan/templates/group/search_rebuild.html
- ckan/templates/organization/edit_base.html
- ckan/templates/organization/search_rebuild.html
- ckan/views/admin.py
- ckan/views/dataset.py
- ckan/views/group.py
- ckan/views/util.py
Related issues:
* https://github.com/ckan/ckan/issues/7722
* https://github.com/ckan/ckan/issues/5842
Basic issue is that the Org/Group names are in dataset SOLR records. This would be an issue if an Org/Group title or name is updated, their dataset's won't show this in `package_search` or anything else that queries the SOLR index. So this adds some logic functions to re-index an Org/Group's records after the title or name changes.
It does this in a background task. So this would require some documentation regarding that. 
This also implements some task_status stuff for this and adds in some UIs to sysadmins to be able to re-index from the Admin views. And adds a progress bar to see the status of the re-index.
> Search Index Rebuild UI and After Org Update

- changes/186.canada.bugfix
- ckanext/datatablesview/blueprint.py
feat(dev): datatables special chars;
- Search with special characters in datatables view.
Related issue: https://github.com/ckan/ckan/issues/8583
> Allow Special Character Search in DataTables View

- changes/187.canada.bugfix
- ckan/views/user.py
fix(views): password reset deleted users;
- Skip deleted users for password reset.
> No Password Reset for Deleted Users

- changes/188.canada.changes
- ckanext/datastore/backend/postgres.py
feat(logic): ds upsert info;
- Include the original psql error message and code in the upsert errors.
This will allow Recombinant to parse the FK constraint error messages, without showing the pSQL error to the user still.
> Pass DataStore Upsert Original pSQL Error Messages

- changes/190.canada.feature
- ckanext/datastore/blueprint.py
feat(views): ds dump filename;
- Filename for ds dump endpoint.
> DataStore Dump Filename
